Cleaning imports and adding dependencies
choderalab/feflow pull request #10
Opened 2023-11-08 19:53 UTC by ijpulidos

Cleaning unused imports and adding explicitly used dependencies to the CI/test environment file.

Resolves #9

2023-11-08 20:28 UTC, ijpulidos commented
We need to fix #11 that should fix the tests with the current `openfe` 0.14.0 release, before merging this one.

2023-12-07 21:52 UTC, mikemhenry requested changes
I think we should add a pymbar pin and `gufe >=0.9.5` so we don't pull in something old by mistake

2023-12-07 21:52 UTC, mikemhenry commented on devtools/conda-envs/test_env.yaml
> +  - pymbar
```suggestion
  - pymbar <4
```

2023-12-07 21:58 UTC, mikemhenry approved these changes

2023-12-07 22:20 UTC, merged